CREATE TABLE `properties`(
	id INT(11) NOT NULL AUTO_INCREMENT,
	`key` TEXT DEFAULT NULL,
	`value` TEXT DEFAULT NULL,
	application TEXT DEFAULT NULL,
	`profile` TEXT DEFAULT NULL,
	lable TEXT DEFAULT NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;