// <auto-generated />
using System;
using DeliveryService.Models.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliveryService.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliveryService.Models.Entities.Delivery", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeliveryID");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("OrderID")
                        .HasColumnName("OrderID");

                    b.Property<string>("OrderUserID")
                        .HasColumnName("OrderUserID");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnName("UpdatedTime");

                    b.HasKey("ID");

                    b.ToTable("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
